name: voltev
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  path_provider: ^2.1.2
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.2.1
  geolocator: ^13.0.3
  location: ^5.0.0
  http: ^1.2.0
  flutter_google_maps_webservices: ^1.0.1  # âœ… REPLACEMENT
  flutter_neumorphic: ^3.2.0
  animated_text_kit: ^4.2.2
  intl: ^0.18.1
  geocoding: 3.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.0
  lottie: ^2.7.0
  flutter_animate: ^4.1.1+1
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/amptrail.jpg
    - assets/india.jpeg
    - assets/logimg.jpg
    - assets/otpverify.jpg
    - assets/upi.png
    - assets/phonepe.png
    - assets/paytm.png
    - assets/netbanking.png
    - assets/gpay.png
    - assets/card.png
